### ISSUE TITLE
Exception in thread "Thread-4" java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by rminchev1** [rndsolutions/hawkcd#380]
Exception in thread "Thread-4" java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at net.hawkengine.ws.SessionPool.sendToAuthorizedSessions(SessionPool.java:83)
	at net.hawkengine.ws.EndpointConnector.passResultToEndpoint(EndpointConnector.java:16)
	at net.hawkengine.services.PipelineService.update(PipelineService.java:96)
	at net.hawkengine.services.PipelineService.update(PipelineService.java:23)
	at net.hawkengine.core.pipelinescheduler.StatusUpdaterService.updateStatuses(StatusUpdaterService.java:56)
	at net.hawkengine.core.pipelinescheduler.JobAssigner.run(JobAssigner.java:35)
	at java.lang.Thread.run(Thread.java:745)

**Comment by VladislavNikolov** [comment]
Issue similar to #378
